// src/ids.js

// Stations & Equipment IDs
export const STATION = Object.freeze({
    POTATO_BIN:       'potato_bin',
    CUTTING_BOARD:    'cutting_board',
    DEEP_FRYER:       'deep_fryer',
    PLATE_STACK:      'plate_stack',
    COATING_STATION:  'coating_station',
    LETTUCE_BIN:      'lettuce_bin',
    TOMATO_BIN:       'tomato_bin',
    PATTY_BOX:        'patty_box',
    STOVE_TOP:        'stove_top',
    BUN_RACK:         'bun_rack',
    CHEESE_FRIDGE:    'cheese_fridge',
    ONION_BIN:        'onion_bin',
    CHICKEN_BOX:      'chicken_box',
    BREAD_RACK:       'bread_rack',
    TOASTER:          'toaster',
    BACON_PACK:       'bacon_pack',
    PANCAKE_MIX:      'pancake_mix_src',
    STAND_MIXER:      'stand_mixer',
    SYRUP_BOTTLE:     'syrup_bottle',
    EGG_CARTON:       'egg_carton',
    YOGURT_POT:       'yogurt_pot',
    GRANOLA_JAR:      'granola_jar',
    BOWL_STACK:       'bowl_stack',
    BLENDER:          'blender',
    CUP_STACK:        'cup_stack',
    PIZZA_DOUGH:      'pizza_dough_src',
    DOUGH_PRESS:      'dough_press',
    TOMATO_SAUCE:     'tomato_sauce_src',
    MOZZARELLA_BIN:   'mozzarella_bin',
    PIZZA_OVEN:       'pizza_oven',
    SERVING_PASS:     'serving_pass',
    TRASH_BIN:        'trash_bin',
    COUNTER:          'counter',
    COUNTER_CORNER:   'counter_corner',
    COUNTER_WOOD:     'counter_wood',
    TABLE:            'table',
    WALL:             'wall',
    WALL_SHORT:       'wall_short',
    WALL_LONG:        'wall_long',
    WALL_CORNER:      'wall_corner',
    BANANA_CRATE:     'banana_crate',
    STRAWBERRY_BOX:   'strawberry_box',
    MILK_CARTON:      'milk_carton',
    COATING_MIX:      'coating_mix_src'
});

// Utensils & Containers (Assiette, Bol, Gobelet, etc.)
export const UTENSIL = Object.freeze({
    PLATE:            'plate',
    BOWL:             'bowl',
    CUP:              'cup',
    PIZZA_BASE:       'pizza_base',
    BREAD_SLICE:      'bread_slice'
});

// Ingredients & Processed Items
export const INGREDIENT = Object.freeze({
    POTATO:                  'potato',
    RAW_FRIES:               'raw_fries',
    COOKED_FRIES:            'cooked_fries',
    PIZZA_DOUGH:             'pizza_dough',
    SHREDDED_MOZZARELLA:     'shredded_mozzarella',
    TOMATO_SAUCE:            'tomato_sauce',
    RAW_CHICKEN:             'raw_chicken',
    RAW_CHICKEN_STRIPS:      'raw_chicken_strips',
    COATED_CHICKEN_STRIPS:   'coated_chicken_strips',
    COOKED_CHICKEN_TENDERS:  'cooked_chicken_tenders',
    RAW_BACON:               'raw_bacon',
    COOKED_BACON:            'cooked_bacon',
    TOASTED_BREAD:           'toasted_bread',
    EGG:                     'egg',
    MILK:                    'milk',
    YOGURT:                  'yogurt',
    GRANOLA:                 'granola',
    SYRUP:                   'syrup',
    PANCAKE_MIX:             'pancake_mix',
    PANCAKE_BATTER:          'pancake_batter',
    OMELETTE_MIX:            'omelette_mix',
    COOKED_OMELETTE:         'cooked_omelette',
    COOKED_PANCAKES:         'cooked_pancakes',
    RAW_ONION_RINGS:         'raw_onion_rings',
    ONION_RINGS_RAW:         'onion_rings_raw',
    ONION_RINGS_COATED:      'onion_rings_coated',
    COOKED_ONION_RINGS:      'cooked_onion_rings',
    RAW_ONION:               'raw_onion',
    ONION:                   'onion',
    SLICED_ONION:            'sliced_onion',
    BANANA:                  'banana',
    SLICED_BANANA:           'sliced_banana',
    STRAWBERRY:              'strawberry',
    SLICED_STRAWBERRY:       'sliced_strawberry',
    SMOOTHIE_READY:          'smoothie_ready',
    GRILLED_CHEESE_COOKED:   'grilled_cheese_cooked',
    GRILLED_CHEESE_RAW:      'grilled_cheese_raw',
    PIZZA_MARGHERITA_RAW:    'pizza_margherita_raw',
    COOKED_PIZZA_MARGHERITA: 'cooked_pizza_margherita',
    COATING_MIX:             'coating_mix',
    BUN:                     'bun',
    PATTY:                   'patty',
    COOKED_PATTY:            'cooked_patty',
    CHEESE_SLICE:            'cheese_slice',
    LETTUCE:                 'lettuce',
    CHOPPED_LETTUCE:         'chopped_lettuce',
    TOMATO:                  'tomato',
    CHOPPED_TOMATO:          'chopped_tomato'
});

// Meal / Recipe IDs (clés de RECIPES)
export const MEAL = Object.freeze({
    FRENCH_FRIES:            'french_fries',
    SALAD:                   'salad',
    HAMBURGER:               'hamburger',
    CHEESEBURGER_COMBO:      'cheeseburger_combo',
    ONION_RINGS:             'onion_rings',
    CHICKEN_TENDERS_FRIES:   'chicken_tenders_fries',
    BLT_SANDWICH:            'blt_sandwich',
    GRILLED_CHEESE_SANDWICH: 'grilled_cheese_sandwich',
    PANCAKES:                'pancakes',
    CHEESE_OMELETTE:         'cheese_omelette',
    FRUIT_YOGURT_BOWL:       'fruit_yogurt_bowl',
    SMOOTHIE:                'smoothie',
    PIZZA_MARGHERITA:        'pizza_margherita'
});
