// src/ids.js

// Stations & Equipment IDs
export const STATION = Object.freeze({
    POTATO_BIN:       'potato_bin',
    CUTTING_BOARD:    'cutting_board',
    DEEP_FRYER:       'deep_fryer',
    PLATE_STACK:      'plate_stack',
    COATING_STATION:  'coating_station',
    LETTUCE_BIN:      'lettuce_bin',
    TOMATO_BIN:       'tomato_bin',
    PATTY_BOX:        'patty_box',
    STOVE_TOP:        'stove_top',
    BUN_RACK:         'bun_rack',
    CHEESE_FRIDGE:    'cheese_fridge',
    ONION_BIN:        'onion_bin',
    CHICKEN_BOX:      'chicken_box',
    BREAD_RACK:       'bread_rack',
    TOASTER:          'toaster',
    BACON_PACK:       'bacon_pack',
    PANCAKE_MIX:      'pancake_mix_src',
    STAND_MIXER:      'stand_mixer',
    SYRUP_BOTTLE:     'syrup_bottle',
    EGG_CARTON:       'egg_carton',
    YOGURT_POT:       'yogurt_pot',
    GRANOLA_JAR:      'granola_jar',
    BOWL_STACK:       'bowl_stack',
    BLENDER:          'blender',
    CUP_STACK:        'cup_stack',
    PIZZA_DOUGH:      'pizza_dough_src',
    DOUGH_PRESS:      'dough_press',
    TOMATO_SAUCE:     'tomato_sauce_src',
    MOZZARELLA_BIN:   'mozzarella_bin',
    PIZZA_OVEN:       'pizza_oven',
    SERVING_PASS:     'serving_pass',
    TRASH_BIN:        'trash_bin',
    COUNTER:          'counter',
    COUNTER_CORNER:   'counter_corner',
    COUNTER_WOOD:     'counter_wood',
    TABLE:            'table',
    WALL:             'wall',
    WALL_SHORT:       'wall_short',
    WALL_LONG:        'wall_long',
    WALL_CORNER:      'wall_corner',
    BANANA_CRATE:     'banana_crate',
    STRAWBERRY_BOX:   'strawberry_box',
    MILK_CARTON:      'milk_carton',
    COATING_MIX:      'coating_mix_src'
});

// Meal / Recipe IDs (clés de RECIPES)
export const MEAL = Object.freeze({
    FRENCH_FRIES:            'french_fries',
    SALAD:                   'salad',
    HAMBURGER:               'hamburger',
    CHEESEBURGER_COMBO:      'cheeseburger_combo',
    ONION_RINGS:             'onion_rings',
    CHICKEN_TENDERS_FRIES:   'chicken_tenders_fries',
    BLT_SANDWICH:            'blt_sandwich',
    GRILLED_CHEESE_SANDWICH: 'grilled_cheese_sandwich',
    PANCAKES:                'pancakes',
    CHEESE_OMELETTE:         'cheese_omelette',
    FRUIT_YOGURT_BOWL:       'fruit_yogurt_bowl',
    SMOOTHIE:                'smoothie',
    PIZZA_MARGHERITA:        'pizza_margherita'
});
